apiVersion: apps/v1
kind: Deployment
metadata:
  name: american-predictor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matheussouza-american-predictor
  template:
    metadata:
      labels:
        app: matheussouza-american-predictor
    spec:
      containers:
      - name: american-predictor
        image: docker.io/matheuspimenta/american-predictor:0.1
        env:
        - name: MODEL_VERSION
          value: "0.1"
        ports:
        - containerPort: 5024