apiVersion: apps/v1
kind: Deployment
metadata:
  name: american-predictor-deployment
  labels:
    app: matheussouza-american-predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matheussouza-american-predictor
  template:
    metadata:
      labels:
        app: matheussouza-american-predictor
    spec:
      containers:
      - name: matheussouza-american-predictor
        image: docker.io/matheuspimenta/american-predictor:0.3
        env:
        - name: CODE_VERSION
          value: "0.3"
        ports:
        - containerPort: 5024